### ISSUE TITLE
Erro on Telegraf module

### ISSUE THREAD

**Issue by igorssena** [ldurans/izing.io#150]
------
 > [11/14] RUN npm run build:
#0 1.398
#0 1.398 > backend@1.0.0 build /usr/src/app
#0 1.398 > tsc
#0 1.398
#0 15.83 node_modules/telegraf/node_modules/typegram/index.d.ts(10,15): error TS1005: ',' expected.
#0 15.83 node_modules/telegraf/typings/composer.d.ts(7,15): error TS1005: ',' expected.
#0 15.87 npm ERR! code ELIFECYCLE
#0 15.87 npm ERR! errno 2
#0 15.87 npm ERR! backend@1.0.0 build: `tsc`
#0 15.87 npm ERR! Exit status 2
#0 15.87 npm ERR!
#0 15.87 npm ERR! Failed at the backend@1.0.0 build script.
#0 15.87 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#0 15.93
#0 15.93 npm ERR! A complete log of this run can be found in:
#0 15.93 npm ERR!     /root/.npm/_logs/2023-08-31T11_25_05_924Z-debug.log
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 2

**Comment by ldurans** [comment]
Não encontrei este erro na versão 2.0. Atualize e faça novos testes.
