### ISSUE TITLE
Erro ao salvar contato

### ISSUE THREAD

**Issue by ejdoming** [ldurans/izing.io#220]
"Internal server error: SequelizeUniqueConstraintError: Validation error"

**Comment by Disapper** [comment]
Estava com esse mesmo problema e resolvi rodando esse comando abaixo no banco de dados.

> SELECT setval(pg_get_serial_sequence('"Contacts"', 'id'), MAX(id)) FROM "Contacts";


Com isso consegui inserir os contatos normalmente, mais creio que esse erro só ocorreu por conta que peguei os contatos de um banco antigo e importei.

**Comment by amiltomGhub** [comment]
realmente resolveu esse problema obrigado
