### ISSUE TITLE
Error when trying to run the project

### ISSUE THREAD

**Issue by viapratica** [ldurans/izing.io#42]
Error compiling or running docker

Running docker:

  > [izingio-izing-backend 11/14] RUN npm run build:
#0 0.513
#0 0.513 > backend@1.0.0 build /usr/src/app
#0 0.513 > tsc
#0 0.513
#0 16.30 node_modules/@types/express-serve-static-core/index.d.ts(99.68): error TS1110: type expected.
#0 16.30 node_modules/@types/express-serve-static-core/index.d.ts(99.77): TS1005 error: '}' expected.

Compiling manually:

root@vmi675017:/opt/izing.io/backend# npm run build

> backend@1.0.0 build /opt/izing.io/backend
> tsk

error TS2688: Cannot find type definition file for 'pino-pretty'.

1 error found.

npm ERR! ELIFECYCLE code
npm ERR! mistake 2
npm ERR! backend@1.0.0 build: `tsc`
npm ERR! exit state 2
npm ERR!
npm ERR! Build script backend@1.0.0 failed.
npm ERR! This is probably not a problem with npm. There is probably additional log output above.

npm ERR! A complete log of this run can be found at:
npm ERR! /root/.npm/_logs/2022-11-13T20_46_39_485Z-debug.log

**Comment by ldurans** [comment]
In the new version we have adjusted some dependencies and also the typescript lib. Please update and try again.
