### ISSUE TITLE
Erro de  CHATBOT condição se qualquer resposta

### ISSUE THREAD

**Issue by Guilhermealves20101999** [ldurans/izing.io#43]
Quando vou cadastrar o CHATBOT e coloco a condição se qualquer Resposta e quando mando mensagem e respondo qualquer coisa, ele me retorna o erro falando que nao entendeu a minha resposta, e nao segue e condição.

**Comment by ldurans** [comment]
Essa funcionalidade será removida do bot nas próximas versões.
