### ISSUE TITLE
Não é possível cadastrar Campanhas

### ISSUE THREAD

**Issue by rcalbo** [ldurans/izing.io#45]
Ao tentar cadastrar uma campanha, ao tentar selecionar uma opção no campo obrigatório Enviar Por, não aparece opções.

Não encontrei opções no sistema para ajustar esta opção.

![image](https://user-images.githubusercontent.com/47294683/201746859-0a22a69f-5a02-4f0d-b33a-21fd9fd857c8.png)

**Comment by ldurans** [comment]
Update to 1.7.1.
