### ISSUE TITLE
Cadastrar empresa e novo canal

### ISSUE THREAD

**Issue by dlpazinatto** [ldurans/izing.io#55]
Olá, qual o caminho para cadastrar uma segunda empresa, é no admin-front? caso sim, nao estou encontrando.
é possivel adicionar dois canais do mesmo tipo para a mesma empresa? quando tento cadastrar o segundo canal para a empresa -1, da erro. abaixo o log.

error: 2022-11-16T18:04:46.554Z Validation error - SequelizeUniqueConstraintError: Validation error
0|izing-backend  |     at Query.formatError (/home/deploy/izing.io/backend/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)
0|izing-backend  |     at /home/deploy/izing.io/backend/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
0|izing-backend  |     at tryCatcher (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/util.js:16:23)
0|izing-backend  |     at Promise._settlePromiseFromHandler (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/promise.js:547:31)
0|izing-backend  |     at Promise._settlePromise (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/promise.js:604:18)
0|izing-backend  |     at Promise._settlePromise0 (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/promise.js:649:10)
0|izing-backend  |     at Promise._settlePromises (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/promise.js:725:18)
0|izing-backend  |     at _drainQueueStep (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/async.js:93:12)
0|izing-backend  |     at _drainQueue (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/async.js:86:9)
0|izing-backend  |     at Async._drainQueues (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/async.js:102:5)
0|izing-backend  |     at Immediate.Async.drainQueues [as _onImmediate] (/home/deploy/izing.io/backend/node_modules/bluebird/js/release/async.js:15:14)
0|izing-backend  |     at processImmediate (internal/timers.js:464:21)

Obrigado

**Comment by dlpazinatto** [comment]
Obrigado @7h1-4-g0 . No momento tem alguma forma de cadastrar mais que uma empresa? 
valeu

**Comment by ldurans** [comment]
Inserções somente via DB.

**Comment by codsec** [comment]
> Inserções somente via DB.

Tem algum exemplo ou tutorial sobre isso? eu preciso de adicionar 3 numeros de whatsapp diferentes, e dedicar eles para filas diferentes, exatamente igual ao whaticket faz(porem ele está 100% desatualizado impossivel de usar)
