### ISSUE TITLE
Opção Deletar mensagem não está habilitada

### ISSUE THREAD

**Issue by patronotech** [ldurans/izing.io#57]
Opção de deletar mensagem não está habilitando mesmo estando dentro do prazo de 5 minutos estabelecido pelo sistema

![image](https://user-images.githubusercontent.com/107273923/202358444-f222ed53-61dd-4d36-9e2c-67ade4475530.png)

**Comment by Silvioerick** [comment]
Esta com mesmo erro aqui.

**Comment by ldurans** [comment]
Resolvido, só atualizar.
