### ISSUE TITLE
Erro ao logar Admin FrontEnd

### ISSUE THREAD

**Issue by andersonkida** [ldurans/izing.io#63]
Quando é feito o login ele já sai do painel falando que a sessão expirou.

![WhatsApp Image 2022-11-20 at 19 53 00](https://user-images.githubusercontent.com/33435785/203050807-4efbcc3b-557f-4a52-b286-05fe29dbf893.jpeg)

**Comment by ldurans** [comment]
O Admin é apenas um esquema inicial. Desconsiderem essa aplicação, por hora.
