### ISSUE TITLE
BUG mais de 1 conexao de whatsapp

### ISSUE THREAD

**Issue by Silvioerick** [ldurans/izing.io#65]
Quando conecto mais de 1 conexao de whatsapp, mesmo uma sendo default, ela começa a alternar as conexoes qdo se responde um chamado, exempo..
Cadastrei Whatsapp 1 , 2 e 3
eu chamo no Whatsapp 1 , qdo respondo o cliente ele sai pelo whatsapp 2 ou 3 e vai alternando, mesmo estando em tenant diferente.

**Comment by Silvioerick** [comment]
Corrigido na versao 1.7.3

**Comment by codsec** [comment]
> Quando conecto mais de 1 conexao de whatsapp, mesmo uma sendo default, ela começa a alternar as conexoes qdo se responde um chamado, exempo.. Cadastrei Whatsapp 1 , 2 e 3 eu chamo no Whatsapp 1 , qdo respondo o cliente ele sai pelo whatsapp 2 ou 3 e vai alternando, mesmo estando em tenant diferente.

Como faço para conectar mais de 1 whatsapp? tem como fazer uma breve explicação ai, pois fucei no frontend e não consegui achar nada sobre

**Comment by Silvioerick** [comment]
Verifica no banco de dados a tabela Settings deve estar duplicado la por isso esta dando esses erros.
,

**Comment by codsec** [comment]
> Verifica no banco de dados a tabela Settings deve estar duplicado la por isso esta dando esses erros. ,

Oq isso tem haver com oq eu perguntei kk
