### ISSUE TITLE
erro durante o npx sequelize db:migrate e npx sequelize db:seed:all

### ISSUE THREAD

**Issue by carloslencargorges** [ldurans/izing.io#68]
sempre que tento realizar ambos os comandos são retornados os seguintes erros:
![image](https://user-images.githubusercontent.com/98112671/203457843-173f8bdd-56e6-4870-b21d-06a000af53e1.png)
![image](https://user-images.githubusercontent.com/98112671/203457868-f71161b5-6111-40ca-b5b7-84562400c688.png)
qualquer ajuda é bem-vinda!

**Comment by ldurans** [comment]
Duplicado.
Verifique a issue #64
