### ISSUE TITLE
Algumas sugestoes e 1 bug que achei.

### ISSUE THREAD

**Issue by Silvioerick** [ldurans/izing.io#72]
---BUG---
Nao esta funcionando a parte de notificações de som quando chega mensagem.

---SUGESTÕES---
No whaticket tem o popup tambem porem esta encrito em react, nao sei se tem na linguagem que usa no front ni izing essa opcao

Na tela de ticket mostrar no ticket qual conexao esta usando em caso de ter mais de 1 whatsapp ou outro, mostrar o nome da conexao embaixo do nome.

Ter um botao de selecao no chat para ocultar ou nao o nome do usuario na resposta.

**Comment by codsec** [comment]
> ---BUG--- Nao esta funcionando a parte de notificações de som quando chega mensagem.
> 
> ---SUGESTÕES--- No whaticket tem o popup tambem porem esta encrito em react, nao sei se tem na linguagem que usa no front ni izing essa opcao
> 
> Na tela de ticket mostrar no ticket qual conexao esta usando em caso de ter mais de 1 whatsapp ou outro, mostrar o nome da conexao embaixo do nome.
> 
> Ter um botao de selecao no chat para ocultar ou nao o nome do usuario na resposta.

Como faço para ter mais de um whatsapp?
