### ISSUE TITLE
Izing não loga apos instalação pelo docker

### ISSUE THREAD

**Issue by Natan738** [ldurans/izing.io#73]
Após a instação pelo docker não consigo logar usando o login : admin@izing.io e senha: 123456
alguém consegui me ajudar?

**Comment by Silvioerick** [comment]
Verifica todos os docker se estao ativos e reniciar eles todos..., roda o npm start no backend e ve se da algum erro

**Comment by ldurans** [comment]
Se o problema persistir, abrar uma nova issue e apresente logs, prints, fluxo executado e detalhe o máximo possível.
