### ISSUE TITLE
Filas, chatbot e atendimento não funcionam

### ISSUE THREAD

**Issue by Smallkan** [ldurans/izing.io#79]
Atendimento funciona normal quando não há filas cadastradas.

Ao cadastrar uma nova fila, não aparece nenhum ticket no atendimento, além disso, o chatbot não funciona, testei com vários números, incluindo business com e sem chrome.

Alguém dá uma luz?

**Comment by ldurans** [comment]
Após cadastrado uma fila, é necessário realizar a liberação para o usuário. Se existirem filas, o sistema entenderá que somente quem tiver acesso às filas poderá acessar os atendimentos.

Sobre o chatbot, é impossível dizer sem apresentar prints do fluxo, logs... Verifique se configurou um número de teste, se adicionou o fluxo como ativo nas configurações. Irão entrar no fluxo os contatos que não tiverem atendimento aberto. 
Bom entender o fluxo do código.

**Comment by Smallkan** [comment]
Oi, peço desculpas pela falta de detalhes.

Estou executando no windows, usando o "dev:server" no backend e quasar dev no frontend, não há erros no console, a conexão foi feita. Enviei uma mensagem de outro número e não há resposta do BOT.
![image](https://user-images.githubusercontent.com/9128062/206793424-bd056274-636f-4253-8a45-d71f87f3068d.png)

Aqui está a configuração do CHATBOT, atualmente possui 2 filas cadastradas.
![image](https://user-images.githubusercontent.com/9128062/206793574-a411e479-9257-4a8c-a0a4-8886a3f05d10.png)
![image](https://user-images.githubusercontent.com/9128062/206793670-accc9cdf-ae20-44a8-a601-912d7b17f8cd.png)
![image](https://user-images.githubusercontent.com/9128062/206793972-6e26d892-b3d7-4259-af38-64fb9f3bc083.png)

Mesmo sem o CHATBOT, ele inativo, não funciona auto resposta ou o balanceamento, preciso entender mais sobre essa auto resposta, pois até com o número de testes não roda.
